<div class="row-fluid"><div class="span12">
    <div id="header"><h2 class="access">Start of page header</h2>
      <a href="http://evolt.org/" title="Return to the home page" accesskey="1" ><img src="http://evolt.org/themes/evolt/evoltorg.gif" alt="evolt.org" title="Welcome to evolt.org" id="logo" /></a>
       <h2 class="access"><a name="other-sites">Other Fine Evolt.org Sites</a></h2>
       <ul id="sections">
        <li id="sectionwork"><a href="http://evolt.org/" title="list and articles">Work</a>
          <p>list and articles</p>
        </li>
        <li id="sectiontest"><a href="http://browsers.evolt.org/" title="browser archive">Test</a>
          <p>browser archive</p>
        </li>
        <li id="sectiondonate"><a href="http://evolt.org/help_support_evolt" title="keep evolt.org alive">Donate</a>
          <p>keep evolt.org alive</p>
        </li>
       </ul>
    </div>
</div></div>

<div class="row-fluid"><div class="span12">
<div id="content"><div id="channel">

    <!-- this item really shouldn't be done this way -->

  <p class="work-title"><a href="/">Test</a></p>

  <ul id="secondary">

    <li><a href="http://evolt.org/about">About Us</a></li><li><a href="http://lists.evolt.org/">Lists</a></li><li><a href="http://evolt.org/taxonomy/term/23">Jobs</a></li>
  </ul>

  <ul id="secondary-constants">

    <li><a href="http://evolt.org/faq" accesskey="5">FAQ</a></li>

    <li><a href="http://evolt.org/contact" accesskey="9">Contact</a></li>

  </ul>

</div>

<div class="row-fluid" style="background-color: #ffffff">
<div class="span8"><p>&nbsp;</p>
