<?php
// browserarchive.org aka browsers.evolt.org
// Copyright (c) 1999-2013 Adrian Roselli, William Anderson
?>
	<section id="slider">
	<a href="javascript:void(0)" class="prev1"></a>
	<a href="javascript:void(0)" class="next1"></a>
	<ul id="slides">
		<li class="slide">
		<div class="wrapper">
			<div class="slide-text">
				<p class="sub-heading-upper">Workers of the web, unite!</p>
				<p class="big">Welcome to evolt.org</p>
				<p>Mailing list discussions. Legacy browsers for testing. An article archive spanning 15 years. Join one of the world's longest-running web design communities.</p>
			</div>
			<div class="slide-image">
				<img src="/assets/images/slide-image-4.png" alt="" />
			</div>
		</div>
		<div class="slide-back">
			<!-- no background image for this slide -->
		</div>
		</li>
		<li class="slide">
		<div class="wrapper">
			<div class="slide-text">
				<p class="sub-heading-upper">1998</p>
				<p class="big">Workers of the web, unite!</p>
				<p>An exodus of members of the WIRED MonkeyJunkies web development community leads to the formation of <strong>evolt.org</strong>.</p>
			</div>
			<div class="slide-image">
				<img src="/assets/img/slides-1998-evolt-alpha.png" alt="" />
			</div>
		</div>
		<div class="slide-back">
			<!-- no background image for this slide -->
		</div>
		</li>
		<li class="slide">
		<div class="wrapper">
			<div class="slide-text">
				<p class="sub-heading-upper">1999</p>
				<p class="big">Something exciting</p>
				<p><strong>evolt.org</strong> becomes more than a mailing list, building a site to hold articles written by community members.</p>
			</div>
			<div class="slide-image">
				<img src="/assets/img/slides-1999-evolt-onepointoh.png" alt="" />
			</div>
		</div>
		<div class="slide-back">
			<!-- no background image for this slide -->
		</div>
		</li>
		<li class="slide">
		<div class="wrapper">
			<div class="slide-text">
				<p class="sub-heading-upper">2000</p>
				<p class="big">More excitement</p>
				<p>The site is upgraded again, with a new design reflecting improvements in HTML and CSS.</p>
			</div>
			<div class="slide-image">
				<img src="/assets/img/slides-2000-evolt-twopointoh.png" alt="" />
			</div>
		</div>
		<div class="slide-back">
			<!-- no background image for this slide -->
		</div>
		</li>
		<li class="slide">
		<div class="wrapper">
			<div class="slide-text">
				<p class="sub-heading-upper">2005</p>
				<p class="big">I can't take this</p>
				<p><strong>evolt.org</strong> three-point-oh: a new foundation built upon an industrial-grade CMS, and modern web standards.</p>
			</div>
			<div class="slide-image">
				<img src="/assets/img/slides-2005-evolt-threepointoh.png" alt="" />
			</div>
		</div>
		<div class="slide-back">
			<!-- no background image for this slide -->
		</div>
		</li>
	</ul>
	</section>