<?php ?>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="generator" content="beo 3.0b0"/>
<title>browsers.evolt.org | Workers of the Web, Evolt!</title>
<link rel="icon" type="image/vnd.microsoft.icon" href="/favicon.ico" />
<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,800" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet' type='text/css' />
<link rel="stylesheet" type="text/css" href="/assets/external/bootstrap/css/bootstrap.min.css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="/assets/external/bootstrap/js/bootstrap.min.js"></script>
<style type="text/css" media="all">@import "http://evolt.org/themes/evolt/style.css";</style>
<link rel="stylesheet" type="text/css" href="/assets/css/beo.css" />
</head>
<body>

<!-- container --><div class="container-fluid">
